/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ExternalDecoderInterface extends ethers.utils.Interface {
  functions: {
    "decodeString(bytes)": FunctionFragment;
    "decodeUint8(bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "decodeString",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "decodeUint8",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "decodeString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decodeUint8",
    data: BytesLike
  ): Result;

  events: {};
}

export class ExternalDecoder extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ExternalDecoderInterface;

  functions: {
    decodeString(
      _input: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      result: string;
      0: string;
    }>;

    "decodeString(bytes)"(
      _input: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      result: string;
      0: string;
    }>;

    decodeUint8(
      _input: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      result: number;
      0: number;
    }>;

    "decodeUint8(bytes)"(
      _input: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      result: number;
      0: number;
    }>;
  };

  decodeString(_input: BytesLike, overrides?: CallOverrides): Promise<string>;

  "decodeString(bytes)"(
    _input: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  decodeUint8(_input: BytesLike, overrides?: CallOverrides): Promise<number>;

  "decodeUint8(bytes)"(
    _input: BytesLike,
    overrides?: CallOverrides
  ): Promise<number>;

  callStatic: {
    decodeString(_input: BytesLike, overrides?: CallOverrides): Promise<string>;

    "decodeString(bytes)"(
      _input: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    decodeUint8(_input: BytesLike, overrides?: CallOverrides): Promise<number>;

    "decodeUint8(bytes)"(
      _input: BytesLike,
      overrides?: CallOverrides
    ): Promise<number>;
  };

  filters: {};

  estimateGas: {
    decodeString(
      _input: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "decodeString(bytes)"(
      _input: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    decodeUint8(
      _input: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "decodeUint8(bytes)"(
      _input: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    decodeString(
      _input: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "decodeString(bytes)"(
      _input: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    decodeUint8(
      _input: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "decodeUint8(bytes)"(
      _input: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
