/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IL2EthInitializable } from "./IL2EthInitializable";

export class IL2EthInitializableFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IL2EthInitializable {
    return new Contract(address, _abi, signerOrProvider) as IL2EthInitializable;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_l2Bridge",
        type: "address",
      },
    ],
    name: "initialization",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
