/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IL2Messenger } from "./IL2Messenger";

export class IL2MessengerFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IL2Messenger {
    return new Contract(address, _abi, signerOrProvider) as IL2Messenger;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_message",
        type: "bytes",
      },
    ],
    name: "sendToL1",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
