/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IPaymasterFlow } from "./IPaymasterFlow";

export class IPaymasterFlowFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPaymasterFlow {
    return new Contract(address, _abi, signerOrProvider) as IPaymasterFlow;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_minAllowance",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_innerInput",
        type: "bytes",
      },
    ],
    name: "approvalBased",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "input",
        type: "bytes",
      },
    ],
    name: "general",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
