/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IPaymasterFlowInterface extends ethers.utils.Interface {
  functions: {
    "approvalBased(address,uint256,bytes)": FunctionFragment;
    "general(bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "approvalBased",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "general", values: [BytesLike]): string;

  decodeFunctionResult(
    functionFragment: "approvalBased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "general", data: BytesLike): Result;

  events: {};
}

export class IPaymasterFlow extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IPaymasterFlowInterface;

  functions: {
    approvalBased(
      _token: string,
      _minAllowance: BigNumberish,
      _innerInput: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "approvalBased(address,uint256,bytes)"(
      _token: string,
      _minAllowance: BigNumberish,
      _innerInput: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    general(
      input: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "general(bytes)"(
      input: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  approvalBased(
    _token: string,
    _minAllowance: BigNumberish,
    _innerInput: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "approvalBased(address,uint256,bytes)"(
    _token: string,
    _minAllowance: BigNumberish,
    _innerInput: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  general(
    input: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "general(bytes)"(
    input: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    approvalBased(
      _token: string,
      _minAllowance: BigNumberish,
      _innerInput: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "approvalBased(address,uint256,bytes)"(
      _token: string,
      _minAllowance: BigNumberish,
      _innerInput: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    general(input: BytesLike, overrides?: CallOverrides): Promise<void>;

    "general(bytes)"(
      input: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    approvalBased(
      _token: string,
      _minAllowance: BigNumberish,
      _innerInput: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "approvalBased(address,uint256,bytes)"(
      _token: string,
      _minAllowance: BigNumberish,
      _innerInput: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    general(input: BytesLike, overrides?: Overrides): Promise<BigNumber>;

    "general(bytes)"(
      input: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    approvalBased(
      _token: string,
      _minAllowance: BigNumberish,
      _innerInput: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "approvalBased(address,uint256,bytes)"(
      _token: string,
      _minAllowance: BigNumberish,
      _innerInput: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    general(
      input: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "general(bytes)"(
      input: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
