/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { DiamondProxyTest } from "./DiamondProxyTest";

export class DiamondProxyTestFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<DiamondProxyTest> {
    return super.deploy(overrides || {}) as Promise<DiamondProxyTest>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): DiamondProxyTest {
    return super.attach(address) as DiamondProxyTest;
  }
  connect(signer: Signer): DiamondProxyTestFactory {
    return super.connect(signer) as DiamondProxyTestFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DiamondProxyTest {
    return new Contract(address, _abi, signerOrProvider) as DiamondProxyTest;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bool",
        name: "_freeze",
        type: "bool",
      },
    ],
    name: "setFreezability",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060fb8061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063bf52956914602d575b600080fd5b608c6038366004609e565b7fc8fcad8db84d3cc18b4c41d551ea0ee66dd599cde068d998e57d5e09332c131e805460ff19169115159190911790557f33774e659306e47509050e97cb651e731180a42d458212294d30751925c551a290565b60405190815260200160405180910390f35b60006020828403121560af57600080fd5b8135801515811460be57600080fd5b939250505056fea2646970667358221220b06281a432b2a39f8b4d1e469d73806261f73ad300284b7a5cd776304e197e0964736f6c63430008110033";
