/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IContractDeployerInterface extends ethers.utils.Interface {
  functions: {
    "create2(bytes32,bytes32,bytes)": FunctionFragment;
    "forceDeployOnAddresses(tuple[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "create2",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "forceDeployOnAddresses",
    values: [
      {
        bytecodeHash: BytesLike;
        newAddress: string;
        value: BigNumberish;
        input: BytesLike;
      }[]
    ]
  ): string;

  decodeFunctionResult(functionFragment: "create2", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "forceDeployOnAddresses",
    data: BytesLike
  ): Result;

  events: {};
}

export class IContractDeployer extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IContractDeployerInterface;

  functions: {
    create2(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "create2(bytes32,bytes32,bytes)"(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    forceDeployOnAddresses(
      _deployParams: {
        bytecodeHash: BytesLike;
        newAddress: string;
        value: BigNumberish;
        input: BytesLike;
      }[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "forceDeployOnAddresses(tuple[])"(
      _deployParams: {
        bytecodeHash: BytesLike;
        newAddress: string;
        value: BigNumberish;
        input: BytesLike;
      }[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  create2(
    _salt: BytesLike,
    _bytecodeHash: BytesLike,
    _input: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "create2(bytes32,bytes32,bytes)"(
    _salt: BytesLike,
    _bytecodeHash: BytesLike,
    _input: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  forceDeployOnAddresses(
    _deployParams: {
      bytecodeHash: BytesLike;
      newAddress: string;
      value: BigNumberish;
      input: BytesLike;
    }[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "forceDeployOnAddresses(tuple[])"(
    _deployParams: {
      bytecodeHash: BytesLike;
      newAddress: string;
      value: BigNumberish;
      input: BytesLike;
    }[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    create2(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "create2(bytes32,bytes32,bytes)"(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    forceDeployOnAddresses(
      _deployParams: {
        bytecodeHash: BytesLike;
        newAddress: string;
        value: BigNumberish;
        input: BytesLike;
      }[],
      overrides?: CallOverrides
    ): Promise<void>;

    "forceDeployOnAddresses(tuple[])"(
      _deployParams: {
        bytecodeHash: BytesLike;
        newAddress: string;
        value: BigNumberish;
        input: BytesLike;
      }[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    create2(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "create2(bytes32,bytes32,bytes)"(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    forceDeployOnAddresses(
      _deployParams: {
        bytecodeHash: BytesLike;
        newAddress: string;
        value: BigNumberish;
        input: BytesLike;
      }[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "forceDeployOnAddresses(tuple[])"(
      _deployParams: {
        bytecodeHash: BytesLike;
        newAddress: string;
        value: BigNumberish;
        input: BytesLike;
      }[],
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    create2(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "create2(bytes32,bytes32,bytes)"(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    forceDeployOnAddresses(
      _deployParams: {
        bytecodeHash: BytesLike;
        newAddress: string;
        value: BigNumberish;
        input: BytesLike;
      }[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "forceDeployOnAddresses(tuple[])"(
      _deployParams: {
        bytecodeHash: BytesLike;
        newAddress: string;
        value: BigNumberish;
        input: BytesLike;
      }[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
