/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IContractDeployer } from "./IContractDeployer";

export class IContractDeployerFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IContractDeployer {
    return new Contract(address, _abi, signerOrProvider) as IContractDeployer;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_salt",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "_bytecodeHash",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "_input",
        type: "bytes",
      },
    ],
    name: "create2",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "bytecodeHash",
            type: "bytes32",
          },
          {
            internalType: "address",
            name: "newAddress",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "value",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "input",
            type: "bytes",
          },
        ],
        internalType: "struct IContractDeployer.ForceDeployment[]",
        name: "_deployParams",
        type: "tuple[]",
      },
    ],
    name: "forceDeployOnAddresses",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
