/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface MerkleTestInterface extends ethers.utils.Interface {
  functions: {
    "calculateRoot(bytes32[],uint256,bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "calculateRoot",
    values: [BytesLike[], BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateRoot",
    data: BytesLike
  ): Result;

  events: {};
}

export class MerkleTest extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: MerkleTestInterface;

  functions: {
    calculateRoot(
      _path: BytesLike[],
      _index: BigNumberish,
      _itemHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "calculateRoot(bytes32[],uint256,bytes32)"(
      _path: BytesLike[],
      _index: BigNumberish,
      _itemHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;
  };

  calculateRoot(
    _path: BytesLike[],
    _index: BigNumberish,
    _itemHash: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "calculateRoot(bytes32[],uint256,bytes32)"(
    _path: BytesLike[],
    _index: BigNumberish,
    _itemHash: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    calculateRoot(
      _path: BytesLike[],
      _index: BigNumberish,
      _itemHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "calculateRoot(bytes32[],uint256,bytes32)"(
      _path: BytesLike[],
      _index: BigNumberish,
      _itemHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    calculateRoot(
      _path: BytesLike[],
      _index: BigNumberish,
      _itemHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "calculateRoot(bytes32[],uint256,bytes32)"(
      _path: BytesLike[],
      _index: BigNumberish,
      _itemHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    calculateRoot(
      _path: BytesLike[],
      _index: BigNumberish,
      _itemHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "calculateRoot(bytes32[],uint256,bytes32)"(
      _path: BytesLike[],
      _index: BigNumberish,
      _itemHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
